; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool on Sat Jul 07 2018 15:37:48 GMT-0700 (Pacific Daylight Time)
;M83            ; relative extruder moves
;G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z15 F360     ; lift Z by 15mm
G90            ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0