; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Sat Jul 07 2018 15:37:48 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0